# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ControlFieldName
                                 A QGIS plugin
 Little Toolbox which check if fieldname is valid
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-12
        copyright            : (C) 2022 by Alex Wieschmann (GIS-Akademie)
        email                : wieschmann@gis-akademie.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ControlFieldName class from file ControlFieldName.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .control_field_name import ControlFieldName
    return ControlFieldName(iface)
